[2024-06-23T11:47:28.952+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:47:28.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:47:29.000+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:47:28.997+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:47:29.625+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:47:29.608+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:47:29.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:47:29.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.962 seconds
[2024-06-23T11:48:03.992+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:48:04.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:48:04.062+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:48:04.061+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:48:05.696+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:48:05.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:48:05.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:48:06.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 2.546 seconds
[2024-06-23T11:48:41.507+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:48:41.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:48:41.573+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:48:41.571+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:48:43.540+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:48:43.155+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:48:43.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:48:44.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 3.213 seconds
[2024-06-23T11:49:16.102+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:49:16.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:49:16.176+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:49:16.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:49:16.401+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:49:16.374+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:49:16.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:49:17.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.934 seconds
[2024-06-23T11:49:48.191+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:49:48.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:49:48.254+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:49:48.253+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:49:48.447+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:49:48.433+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:49:48.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:49:48.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.403 seconds
[2024-06-23T11:50:19.112+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:50:19.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:50:19.121+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:50:19.120+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:50:19.242+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:50:19.218+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:50:19.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:50:19.388+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.296 seconds
[2024-06-23T11:50:49.951+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:50:49.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:50:49.955+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:50:49.954+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:50:49.988+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:50:49.983+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:50:49.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:50:50.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.096 seconds
[2024-06-23T11:51:20.421+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:51:20.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:51:20.428+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:51:20.426+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:51:20.478+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:51:20.458+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:51:20.483+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:51:20.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.108 seconds
[2024-06-23T11:51:50.924+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:51:50.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:51:50.929+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:51:50.928+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:51:50.970+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:51:50.964+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:51:50.972+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:51:51.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.125 seconds
[2024-06-23T11:52:21.513+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:52:21.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:52:21.517+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:52:21.517+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:52:21.570+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:52:21.561+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:52:21.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:52:21.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.110 seconds
[2024-06-23T11:52:52.175+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:52:52.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:52:52.191+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:52:52.182+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:52:52.260+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:52:52.243+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:52:52.264+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:52:52.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.174 seconds
[2024-06-23T11:53:23.024+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:53:23.026+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:53:23.029+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:53:23.028+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:53:23.087+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:53:23.080+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:53:23.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:53:23.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.243 seconds
[2024-06-23T11:53:53.591+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:53:53.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:53:53.596+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:53:53.596+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:53:53.664+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:53:53.639+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:53:53.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:53:53.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.164 seconds
[2024-06-23T11:54:23.936+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:54:23.938+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:54:23.941+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:54:23.941+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:54:23.985+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:54:23.976+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:54:23.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:54:24.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.099 seconds
[2024-06-23T11:54:54.383+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:54:54.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:54:54.388+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:54:54.387+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:54:54.421+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:54:54.413+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:54:54.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:54:54.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.169 seconds
[2024-06-23T11:55:24.974+0000] {processor.py:161} INFO - Started process (PID=276) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:55:24.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:55:24.978+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:55:24.978+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:55:25.013+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:55:25.009+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:55:25.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:55:25.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.101 seconds
[2024-06-23T11:55:55.642+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:55:55.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:55:55.654+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:55:55.653+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:55:55.700+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:55:55.694+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:55:55.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:55:55.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.126 seconds
[2024-06-23T11:56:25.951+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:56:25.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:56:25.957+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:56:25.956+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:56:26.008+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:56:26.001+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:56:26.012+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:56:26.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.174 seconds
[2024-06-23T11:56:56.424+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:56:56.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:56:56.429+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:56:56.428+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:56:56.491+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:56:56.473+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:56:56.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:56:56.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.115 seconds
[2024-06-23T11:57:27.029+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:57:27.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:57:27.034+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:57:27.033+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:57:27.078+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:57:27.070+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:57:27.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:57:27.150+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.126 seconds
[2024-06-23T11:57:57.509+0000] {processor.py:161} INFO - Started process (PID=301) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:57:57.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:57:57.521+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:57:57.519+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:57:57.566+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:57:57.559+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:57:57.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:57:57.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.129 seconds
[2024-06-23T11:58:27.850+0000] {processor.py:161} INFO - Started process (PID=306) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:58:27.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:58:27.887+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:58:27.886+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:58:27.933+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:58:27.926+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:58:27.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:58:27.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.155 seconds
[2024-06-23T11:58:58.428+0000] {processor.py:161} INFO - Started process (PID=311) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:58:58.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:58:58.433+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:58:58.432+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:58:58.469+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:58:58.463+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:58:58.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:58:58.509+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.086 seconds
[2024-06-23T11:59:28.824+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:59:28.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:59:28.831+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:59:28.830+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:59:28.883+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:59:28.877+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:59:28.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:59:28.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.114 seconds
[2024-06-23T11:59:59.586+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:59:59.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T11:59:59.601+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:59:59.600+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T11:59:59.961+0000] {logging_mixin.py:188} INFO - [2024-06-23T11:59:59.922+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T11:59:59.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:00:00.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.610 seconds
[2024-06-23T12:00:30.658+0000] {processor.py:161} INFO - Started process (PID=326) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:00:30.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:00:30.664+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:00:30.663+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:00:30.732+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:00:30.700+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:00:30.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:00:30.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.233 seconds
[2024-06-23T12:01:01.289+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:01:01.294+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:01:01.297+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:01:01.296+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:01:01.335+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:01:01.328+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:01:01.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:01:01.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.126 seconds
[2024-06-23T12:01:31.933+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:01:31.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:01:31.958+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:01:31.957+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:01:31.992+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:01:31.987+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:01:31.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:01:32.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.122 seconds
[2024-06-23T12:02:02.262+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:02:02.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:02:02.328+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:02:02.327+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:02:02.388+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:02:02.380+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:02:02.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:02:02.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.185 seconds
[2024-06-23T12:02:32.849+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:02:32.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:02:32.864+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:02:32.863+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:02:32.912+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:02:32.906+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:02:32.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:02:32.983+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.151 seconds
[2024-06-23T12:03:03.432+0000] {processor.py:161} INFO - Started process (PID=351) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:03:03.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:03:03.438+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:03:03.436+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:03:03.497+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:03:03.490+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:03:03.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:03:03.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.157 seconds
[2024-06-23T12:03:33.722+0000] {processor.py:161} INFO - Started process (PID=356) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:03:33.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:03:33.727+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:03:33.726+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:03:33.796+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:03:33.787+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:03:33.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:03:33.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.158 seconds
[2024-06-23T12:04:04.105+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:04:04.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:04:04.109+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:04:04.108+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:04:04.143+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:04:04.137+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:04:04.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:04:04.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.098 seconds
[2024-06-23T12:04:34.473+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:04:34.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:04:34.478+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:04:34.477+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:04:34.511+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:04:34.505+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:04:34.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:04:34.556+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.089 seconds
[2024-06-23T12:05:04.994+0000] {processor.py:161} INFO - Started process (PID=371) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:05:04.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:05:04.999+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:05:04.998+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:05:05.033+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:05:05.026+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:05:05.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:05:05.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.087 seconds
[2024-06-23T12:05:35.346+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:05:35.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:05:35.359+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:05:35.359+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:05:35.399+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:05:35.393+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:05:35.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:05:35.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.099 seconds
[2024-06-23T12:06:05.898+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:06:05.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:06:05.903+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:06:05.902+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:06:05.942+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:06:05.934+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:06:05.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:06:06.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.108 seconds
[2024-06-23T12:06:36.555+0000] {processor.py:161} INFO - Started process (PID=386) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:06:36.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:06:36.562+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:06:36.561+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:06:36.609+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:06:36.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:06:36.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:06:36.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.128 seconds
[2024-06-23T12:07:07.002+0000] {processor.py:161} INFO - Started process (PID=391) to work on /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:07:07.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_sentiment_analysis.py for tasks to queue
[2024-06-23T12:07:07.006+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:07:07.006+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:07:07.064+0000] {logging_mixin.py:188} INFO - [2024-06-23T12:07:07.056+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_sentiment_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_sentiment_analysis.py", line 31, in <module>
    python_callable=finnhub_mongodb_loader.extract_load
AttributeError: module 'finnhub_mongodb_loader' has no attribute 'extract_load'
[2024-06-23T12:07:07.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_sentiment_analysis.py
[2024-06-23T12:07:07.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_sentiment_analysis.py took 0.145 seconds
